#!/usr/bin/env python3

# TODO
import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline as gut


def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets word")  
        
     # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    user = (str(sys.argv[1])).strip('@')
    number_tweet = 50
    tweets = gut(user,number_tweet)
    
    if tweets is None:
        print("Sorry user is private or could not be found")
        sys.exit("Usage: ./tweets")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{}  {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{}  {}".format(score, tweet), "red"))
        else:
            print(colored("{}  {}".format(score, tweet), "yellow"))
            
if __name__ == "__main__":
    main()
        
        
        